#@copyright : Seif
CC=arm-none-eabi-
CFLAGS=-g -mcpu=arm926ej-s
INCS =-I .
LIBS =
SRC =$(wildcard *.c)
OBJ=$(SRC:.c=.o)
As=$(wildcard *.s)
AsOBJ=$(As:.s=.o)
project_name=learn-in-depth

all:$(project_name).bin
	@echo ">>>>>>Build is Done<<<<<<"

startup.o : startup.s
	$(CC)as.exe $(CFLAGS) $< -o $@
	
%.o : %.c
	$(CC)gcc.exe -c $(CFLAGS) $(INCS) $< -o $@

$(project_name).elf : $(OBJ) $(AsOBJ)
	$(CC)ld -T linker_script.ld $(LIBS) $(OBJ) $(AsOBJ) -o $@

$(project_name).bin: $(project_name).elf
	$(CC)objcopy.exe -O binary $< $@
	
clean_all:
	rm *.o *.elf *.bin

clean:
	rm *.elf *.bin